# Change these first
owner: ChristmanGit # Your GitHub organization or username, where this repository lives
repo: test-up # The name of this repository

sites:
  - name: TribLIVE
    url: https://triblive.com
  - name: TribTotalMedia
    url: https://tribtotalmedia.com
  - name: HSSN
    url: https://tribhssn.triblive.com
  - name: Pennysaver
    url: https://pittsburghpennysaver.com
  - name: Best of the Best
    url: https://bestofthebest.triblive.com
  - name: Print Pittsburgh
    url: https://printpittsburgh.com
  - name: Heroes TribLIVE
    url: https://heroes.triblive.com
  - name: Real Estate TribLIVE
    url: https://realestate.triblive.com
  - name: Mediakit TribLIVE
    url: https://mediakit.triblive.com
  - name: HQ Connectivity
    check: "tcp-ping"
    url: 208.103.127.250
    port: 443


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /test-up
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "TribTotalMedia Website Monitoring"
  introMessage: This is an uptime monitioring site
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
